package apiPayloads;

public class PayloadProvider {

    public static String getFormDataPayload(String title) {
        return "{"
            + "\"wrapperList\":["
            + "{"
            + "\"instanceOf\":\"CustomerCase\","
            + "\"relation\":\"Parent\","
            + "\"sequence\":\"CustomerCase-1\","
            + "\"stringJson\":{"
            + "\"subscriberId\":\"TTVC7846\","
            + "\"customerName\":\"TTVC7846\","
            + "\"email\":\"toyota@yahoo.com\","
            + "\"contactNumber\":5554534937,"
            + "\"address\":\"936 Kiehn Route\","
            + "\"latitude\":22.449364023263904,"
            + "\"longitude\":76.2548452482697,"
            + "\"creator\":140228,"
            + "\"caseId\":\"CASE-0000992\","
            + "\"caseType\":{"
            + "\"creator\":null,"
            + "\"createdTime\":null,"
            + "\"lastModifier\":null,"
            + "\"modifiedTime\":null,"
            + "\"acknowledgementSlaTime\":15,"
            + "\"caseTypeId\":\"BI-005\","
            + "\"deleted\":false,"
            + "\"description\":\"Queries or concerns related to billing and payments\","
            + "\"expectedTimeToResolve\":72,"
            + "\"id\":2,"
            + "\"name\":\"Billing Issue\","
            + "\"resolutionSlaTime\":15,"
            + "\"overAllSlaTime\":null,"
            + "\"verificationSlaTime\":15,"
            + "\"caseCaptureFormId\":null,"
            + "\"caseCaptureFormName\":\"Billing Issue form\","
            + "\"workflowId\":null,"
            + "\"workflowName\":\"Billing Issue workflow\","
            + "\"customerType\":\"RETAIL_SUBSCRIBERS\","
            + "\"slaTimeUnit\":\"MINUTE\","
            + "\"ackSlaID\":null,"
            + "\"resolveSlaID\":null,"
            + "\"closedSlaID\":null,"
            + "\"overAllSlaID\":null,"
            + "\"slaAssociationType\":null,"
            + "\"slaTimeUnitType\":null"
            + "},"
            + "\"source\":\"Phone\","
            + "\"severity\":\"Major\","
            + "\"dueDate\":1748587749000,"
            + "\"priority\":\"Medium\","
            + "\"title\":\"" + title + "\","
            + "\"description\":\"<p>hello</p>\","
            + "\"status\":\"New\""
            + "},"
            + "\"gridName\":\"\""
            + "},"
            + "{"
            + "\"instanceOf\":\"CaseBillingIssue\","
            + "\"relation\":\"Parent\","
            + "\"sequence\":\"CaseBillingIssue-1\","
            + "\"stringJson\":{"
            + "\"orderId\":\"ORD-RET-198099\","
            + "\"invoiceNo\":\"INV-000021\","
            + "\"amount\":3999,"
            + "\"billingDate\":1748457000000,"
            + "\"paymentStatus\":\"YET_TO_BE_PAID\","
            + "\"paidAmount\":77777,"
            + "\"paymentDate\":1747938600000"
            + "},"
            + "\"gridName\":\"\""
            + "}"
            + "],"
            + "\"entityRelation\":{"
            + "\"identifier1\":\"CASE-MANAGEMENT_APP_NAME\","
            + "\"identifier2\":\"CustomerCase\","
            + "\"entityType\":\"CustomerCase\","
            + "\"identifier3\":\".CustomerCase.id\""
            + "},"
            + "\"viewName\":\"case_management_billing_issue_copy_copy\","
            + "\"viewId\":\"VB-008867\","
            + "\"applicationName\":\"CASE-MANAGEMENT_APP_NAME\","
            + "\"history\":true"
            + "}";
    }
}
